import { Component, OnInit, Input } from '@angular/core';
import { FormControl } from '@angular/forms';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';
import { Observable } from 'rxjs';
import { map, debounceTime } from 'rxjs/operators';
import { CreateUserComponent } from './create-user/create-user.component';

@Component({
  selector: 'user-list-component',
  templateUrl: './user-list.component.html',
  styleUrls: ['./user-list.component.less']
})
export class UserListComponent implements OnInit {

  @Input() public isFullGrid: boolean;
  @Input() public isDrmUser: boolean;

  public userList = [
     {
        "user_id":"bc94e73a-6ef9-4e8c-fff6-2bd646276aaa",
        "customer_id":"76065f60-6428-11ea-a2c5-6726caa3835f",
        "org_id":"489dc3b9-99dd-c57f-cfd5-dedfd5cc672d",
        "activation_code":96356394,
        "customer_firstname":"Vasanthi",
        "customer_lastname":"",
        "language":[
           "Assamese",
           "Bangla",
           "English",
           "Gujarathi",
           "Hindi",
           "Kannada",
           "Malayalam",
           "Marathi",
           "Odia",
           "Punjabi",
           "Tamil",
           "Telugu",
           "Urdu"
        ],
        "billing_address":"74",
        "mac_address":"12:21:12:12:21:12",
        "stb_type":"MCBS CH4000",
        "billing_city":"Bangalore",
        "billing_pincode":"521045",
        "phone_number":"8425896541",
        "username":"vasanthi@gmail.com",
        "email":"vasanthi@gmail.com",
        "password":null,
        "activity_time_out":0,
        "sale_mac_address":"undefined",
        "get_msg":"Enable",
        "receive_ads":"Enable",
        "show_adult_content":"Disable",
        "account_lock":"Disable",
        "timezone":"(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi",
        "token":null,
        "billing_state":"Karnataka",
        "installation_address":"74",
        "installation_city":"Bangalore",
        "installation_pincode":"521045",
        "installation_state":"Karnataka",
        "landline_number":null,
        "createdAt":"2020-03-12 11:42:32",
        "updatedAt":"2020-03-12 11:42:32",
        "orgname":"Infynect Demo Operator Organization"
     },
     {
        "user_id":"bc94e73a-6ef9-4e8c-fff6-2bd646276aaa",
        "customer_id":"55fec1d0-6428-11ea-a2c5-6726caa3835f",
        "org_id":"489dc3b9-99dd-c57f-cfd5-dedfd5cc672d",
        "activation_code":22304742,
        "customer_firstname":"Vasantha Priya",
        "customer_lastname":"",
        "language":[
           "Assamese",
           "Bangla",
           "English",
           "Gujarathi",
           "Hindi",
           "Kannada",
           "Malayalam",
           "Marathi",
           "Odia",
           "Punjabi",
           "Tamil",
           "Telugu",
           "Urdu"
        ],
        "billing_address":"43",
        "mac_address":"01:01:01:01:10:10",
        "stb_type":"MCBS CH4000",
        "billing_city":"Bangalore",
        "billing_pincode":"524102",
        "phone_number":"9874558258",
        "username":"vasanthapriya@gmail.com",
        "email":"vasanthapriya@gmail.com",
        "password":null,
        "activity_time_out":0,
        "sale_mac_address":"undefined",
        "get_msg":"Enable",
        "receive_ads":"Enable",
        "show_adult_content":"Disable",
        "account_lock":"Disable",
        "timezone":"(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi",
        "token":null,
        "billing_state":"Karnataka",
        "installation_address":"43",
        "installation_city":"Bangalore",
        "installation_pincode":"524102",
        "installation_state":"Karnataka",
        "landline_number":null,
        "createdAt":"2020-03-12 11:41:39",
        "updatedAt":"2020-03-12 11:41:39",
        "orgname":"Infynect Demo Operator Organization"
     },
     {
        "user_id":"bc94e73a-6ef9-4e8c-fff6-2bd646276aaa",
        "customer_id":"31616f80-6428-11ea-a2c5-6726caa3835f",
        "org_id":"489dc3b9-99dd-c57f-cfd5-dedfd5cc672d",
        "activation_code":66045198,
        "customer_firstname":"Tamil",
        "customer_lastname":"",
        "language":[
           "Assamese",
           "Bangla",
           "English",
           "Gujarathi",
           "Hindi",
           "Kannada",
           "Malayalam",
           "Marathi",
           "Odia",
           "Punjabi",
           "Tamil",
           "Telugu",
           "Urdu"
        ],
        "billing_address":"46,New city",
        "mac_address":"15:15:51:51:41:41",
        "stb_type":"MCBS CH4000",
        "billing_city":"Wardha",
        "billing_pincode":"435210",
        "phone_number":"8428131478",
        "username":"tamil@gmail.com",
        "email":"tamil@gmail.com",
        "password":null,
        "activity_time_out":0,
        "sale_mac_address":"undefined",
        "get_msg":"Enable",
        "receive_ads":"Enable",
        "show_adult_content":"Disable",
        "account_lock":"Disable",
        "timezone":"(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi",
        "token":null,
        "billing_state":"Maharashtra",
        "installation_address":"46,New city",
        "installation_city":"Wardha",
        "installation_pincode":"435210",
        "installation_state":"Maharashtra",
        "landline_number":null,
        "createdAt":"2020-03-12 11:40:37",
        "updatedAt":"2020-03-12 11:40:37",
        "orgname":"Infynect Demo Operator Organization"
     },
     {
        "user_id":"bc94e73a-6ef9-4e8c-fff6-2bd646276aaa",
        "customer_id":"f33d72a0-5dd1-11ea-b936-1556dc150c69",
        "org_id":"489dc3b9-99dd-c57f-cfd5-dedfd5cc672d",
        "activation_code":89006685,
        "customer_firstname":"Ashok",
        "customer_lastname":"S",
        "language":[
           "Assamese",
           "Bangla",
           "English",
           "Gujarathi",
           "Hindi",
           "Kannada",
           "Malayalam",
           "Marathi",
           "Odia",
           "Punjabi",
           "Tamil",
           "Telugu",
           "Urdu"
        ],
        "billing_address":"45-A",
        "mac_address":"75:45:15:17:45:78",
        "stb_type":"MCBS CH4000",
        "billing_city":"Malleswaram",
        "billing_pincode":"530068",
        "phone_number":"8541258963",
        "username":"ashok@gmail.com",
        "email":"ashok@gmail.com",
        "password":null,
        "activity_time_out":0,
        "sale_mac_address":"undefined",
        "get_msg":"Enable",
        "receive_ads":"Enable",
        "show_adult_content":"Disable",
        "account_lock":"Disable",
        "timezone":"(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi",
        "token":null,
        "billing_state":"Karnataka",
        "installation_address":"45-A",
        "installation_city":"Malleswaram",
        "installation_pincode":"530068",
        "installation_state":"Karnataka",
        "landline_number":null,
        "createdAt":"2020-03-04 10:08:09",
        "updatedAt":"2020-03-04 13:15:10",
        "orgname":"Infynect Demo Operator Organization"
     },
     {
        "user_id":"bc94e73a-6ef9-4e8c-fff6-2bd646276aaa",
        "customer_id":"a1cb6170-5dd1-11ea-b936-1556dc150c69",
        "org_id":"489dc3b9-99dd-c57f-cfd5-dedfd5cc672d",
        "activation_code":10998433,
        "customer_firstname":"Amirnath",
        "customer_lastname":"",
        "language":[
           "Assamese",
           "Bangla",
           "English",
           "Gujarathi",
           "Hindi",
           "Kannada",
           "Malayalam",
           "Marathi",
           "Odia",
           "Punjabi",
           "Tamil",
           "Telugu",
           "Urdu"
        ],
        "billing_address":"78,New Corner",
        "mac_address":"95:02:76:25:12:45",
        "stb_type":"MCBS CH4000",
        "billing_city":"Malleswaram",
        "billing_pincode":"530068",
        "phone_number":"9876549876",
        "username":"amirnath@gmail.com",
        "email":"amirnath@gmail.com",
        "password":null,
        "activity_time_out":0,
        "sale_mac_address":"undefined",
        "get_msg":"Enable",
        "receive_ads":"Enable",
        "show_adult_content":"Disable",
        "account_lock":"Disable",
        "timezone":"(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi",
        "token":null,
        "billing_state":"Karnataka",
        "installation_address":"78,New Corner",
        "installation_city":"Malleswaram",
        "installation_pincode":"530068",
        "installation_state":"Karnataka",
        "landline_number":null,
        "createdAt":"2020-03-04 10:05:53",
        "updatedAt":"2020-03-04 10:05:53",
        "orgname":"Infynect Demo Operator Organization"
     },
     {
        "user_id":"bc94e73a-6ef9-4e8c-fff6-2bd646276aaa",
        "customer_id":"6de0ab90-5dd1-11ea-b936-1556dc150c69",
        "org_id":"489dc3b9-99dd-c57f-cfd5-dedfd5cc672d",
        "activation_code":75347030,
        "customer_firstname":"Abi",
        "customer_lastname":"",
        "language":[
           "Assamese",
           "Bangla",
           "English",
           "Gujarathi",
           "Hindi",
           "Kannada",
           "Malayalam",
           "Marathi",
           "Odia",
           "Punjabi",
           "Tamil",
           "Telugu",
           "Urdu"
        ],
        "billing_address":"78",
        "mac_address":"45:45:45:47:48:45",
        "stb_type":"MCBS CH4000",
        "billing_city":"Bangalore",
        "billing_pincode":"530068",
        "phone_number":"7896541258",
        "username":"abi@gmail.com",
        "email":"abi@gmail.com",
        "password":null,
        "activity_time_out":0,
        "sale_mac_address":"undefined",
        "get_msg":"Enable",
        "receive_ads":"Enable",
        "show_adult_content":"Disable",
        "account_lock":"Disable",
        "timezone":"(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi",
        "token":null,
        "billing_state":"Karnataka",
        "installation_address":"78",
        "installation_city":"Bangalore",
        "installation_pincode":"530068",
        "installation_state":"Karnataka",
        "landline_number":null,
        "createdAt":"2020-03-04 10:04:26",
        "updatedAt":"2020-03-04 10:04:26",
        "orgname":"Infynect Demo Operator Organization"
     },
     {
        "user_id":"bc94e73a-6ef9-4e8c-fff6-2bd646276aaa",
        "customer_id":"2eba49d0-5dd1-11ea-b936-1556dc150c69",
        "org_id":"489dc3b9-99dd-c57f-cfd5-dedfd5cc672d",
        "activation_code":27536849,
        "customer_firstname":"Kavin",
        "customer_lastname":"",
        "language":[
           "Assamese",
           "Bangla",
           "English",
           "Gujarathi",
           "Hindi",
           "Kannada",
           "Malayalam",
           "Marathi",
           "Odia",
           "Punjabi",
           "Tamil",
           "Telugu",
           "Urdu"
        ],
        "billing_address":"86 A",
        "mac_address":"78:77:74:45:48:78",
        "stb_type":"MCBS CH4000",
        "billing_city":"Bangalore",
        "billing_pincode":"454521",
        "phone_number":"7859654125",
        "username":"kavipriya@gmail.com",
        "email":"kavipriya@gmail.com",
        "password":null,
        "activity_time_out":0,
        "sale_mac_address":"undefined",
        "get_msg":"Enable",
        "receive_ads":"Enable",
        "show_adult_content":"Disable",
        "account_lock":"Disable",
        "timezone":"(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi",
        "token":null,
        "billing_state":"Karnataka",
        "installation_address":"86 A",
        "installation_city":"Bangalore",
        "installation_pincode":"454521",
        "installation_state":"Karnataka",
        "landline_number":null,
        "createdAt":"2020-03-04 10:02:40",
        "updatedAt":"2020-03-04 10:02:40",
        "orgname":"Infynect Demo Operator Organization"
     },
     {
        "user_id":"bc94e73a-6ef9-4e8c-fff6-2bd646276aaa",
        "customer_id":"fad4c410-5dd0-11ea-b936-1556dc150c69",
        "org_id":"489dc3b9-99dd-c57f-cfd5-dedfd5cc672d",
        "activation_code":94999137,
        "customer_firstname":"Santhiya",
        "customer_lastname":"",
        "language":[
           "Assamese",
           "Bangla",
           "English",
           "Gujarathi",
           "Hindi",
           "Kannada",
           "Malayalam",
           "Marathi",
           "Odia",
           "Punjabi",
           "Tamil",
           "Telugu",
           "Urdu"
        ],
        "billing_address":"26 Plaza corner",
        "mac_address":"98:98:56:58:59:65",
        "stb_type":"MCBS CH4000",
        "billing_city":"Karnataka",
        "billing_pincode":"445210",
        "phone_number":"8563210256",
        "username":"santhiya@gmail.com",
        "email":"santhiya@gmail.com",
        "password":null,
        "activity_time_out":0,
        "sale_mac_address":"undefined",
        "get_msg":"Enable",
        "receive_ads":"Enable",
        "show_adult_content":"Disable",
        "account_lock":"Disable",
        "timezone":"(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi",
        "token":null,
        "billing_state":"Karnataka",
        "installation_address":"26 Plaza corner",
        "installation_city":"Karnataka",
        "installation_pincode":"445210",
        "installation_state":"Karnataka",
        "landline_number":null,
        "createdAt":"2020-03-04 10:01:13",
        "updatedAt":"2020-03-04 10:01:13",
        "orgname":"Infynect Demo Operator Organization"
     },
     {
        "user_id":"bc94e73a-6ef9-4e8c-fff6-2bd646276aaa",
        "customer_id":"cd369ab0-5dd0-11ea-b936-1556dc150c69",
        "org_id":"489dc3b9-99dd-c57f-cfd5-dedfd5cc672d",
        "activation_code":60508497,
        "customer_firstname":"Mano",
        "customer_lastname":"",
        "language":[
           "Assamese",
           "Bangla",
           "English",
           "Gujarathi",
           "Hindi",
           "Kannada",
           "Malayalam",
           "Marathi",
           "Odia",
           "Punjabi",
           "Tamil",
           "Telugu",
           "Urdu"
        ],
        "billing_address":"89-S",
        "mac_address":"15:12:15:14:12:15",
        "stb_type":"MCBS CH4000",
        "billing_city":"Manipur",
        "billing_pincode":"456321",
        "phone_number":"9563210258",
        "username":"mano@gmail.com",
        "email":"mano@gmail.com",
        "password":null,
        "activity_time_out":0,
        "sale_mac_address":"undefined",
        "get_msg":"Enable",
        "receive_ads":"Enable",
        "show_adult_content":"Disable",
        "account_lock":"Disable",
        "timezone":"(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi",
        "token":null,
        "billing_state":"Manipur",
        "installation_address":"89-S",
        "installation_city":"Manipur",
        "installation_pincode":"456321",
        "installation_state":"Manipur",
        "landline_number":null,
        "createdAt":"2020-03-04 09:59:56",
        "updatedAt":"2020-03-04 09:59:56",
        "orgname":"Infynect Demo Operator Organization"
     },
     {
        "user_id":"bc94e73a-6ef9-4e8c-fff6-2bd646276aaa",
        "customer_id":"a67249b0-5dd0-11ea-b936-1556dc150c69",
        "org_id":"489dc3b9-99dd-c57f-cfd5-dedfd5cc672d",
        "activation_code":49249280,
        "customer_firstname":"Manoj",
        "customer_lastname":"",
        "language":[
           "Assamese",
           "Bangla",
           "English",
           "Gujarathi",
           "Hindi",
           "Kannada",
           "Malayalam",
           "Marathi",
           "Odia",
           "Punjabi",
           "Tamil",
           "Telugu",
           "Urdu"
        ],
        "billing_address":"56",
        "mac_address":"15:78:15:14:15:12",
        "stb_type":"MCBS CH4000",
        "billing_city":"Bangalore",
        "billing_pincode":"452152",
        "phone_number":"9875412563",
        "username":"manoj@gmail.com",
        "email":"manoj@gmail.com",
        "password":null,
        "activity_time_out":0,
        "sale_mac_address":"undefined",
        "get_msg":"Enable",
        "receive_ads":"Enable",
        "show_adult_content":"Disable",
        "account_lock":"Disable",
        "timezone":"(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi",
        "token":null,
        "billing_state":"Karnataka",
        "installation_address":"56",
        "installation_city":"Bangalore",
        "installation_pincode":"452152",
        "installation_state":"Karnataka",
        "landline_number":null,
        "createdAt":"2020-03-04 09:58:51",
        "updatedAt":"2020-03-04 09:58:51",
        "orgname":"Infynect Demo Operator Organization"
     },
     {
        "user_id":"bc94e73a-6ef9-4e8c-fff6-2bd646276aaa",
        "customer_id":"656f86d0-5dd0-11ea-b936-1556dc150c69",
        "org_id":"489dc3b9-99dd-c57f-cfd5-dedfd5cc672d",
        "activation_code":14574126,
        "customer_firstname":"Shree",
        "customer_lastname":"",
        "language":[
           "Assamese",
           "Bangla",
           "English",
           "Gujarathi",
           "Hindi",
           "Kannada",
           "Malayalam",
           "Marathi",
           "Odia",
           "Punjabi",
           "Tamil",
           "Telugu",
           "Urdu"
        ],
        "billing_address":"89,257-A",
        "mac_address":"",
        "stb_type":"MCBS CH4000",
        "billing_city":"Delhi",
        "billing_pincode":"414425",
        "phone_number":"9854125896",
        "username":"shree@gmail.com",
        "email":"shree@gmail.com",
        "password":null,
        "activity_time_out":0,
        "sale_mac_address":"undefined",
        "get_msg":"Enable",
        "receive_ads":"Enable",
        "show_adult_content":"Disable",
        "account_lock":"Disable",
        "timezone":"(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi",
        "token":null,
        "billing_state":"Delhi",
        "installation_address":"89,257-A",
        "installation_city":"Delhi",
        "installation_pincode":"414425",
        "installation_state":"Delhi",
        "landline_number":null,
        "createdAt":"2020-03-04 09:57:02",
        "updatedAt":"2020-03-04 09:57:02",
        "orgname":"Infynect Demo Operator Organization"
     },
     {
        "user_id":"bc94e73a-6ef9-4e8c-fff6-2bd646276aaa",
        "customer_id":"3b9f7c70-5dd0-11ea-b936-1556dc150c69",
        "org_id":"489dc3b9-99dd-c57f-cfd5-dedfd5cc672d",
        "activation_code":93340303,
        "customer_firstname":"Balaji",
        "customer_lastname":"",
        "language":[
           "Assamese",
           "Bangla",
           "English",
           "Gujarathi",
           "Hindi",
           "Kannada",
           "Malayalam",
           "Marathi",
           "Odia",
           "Punjabi",
           "Tamil",
           "Telugu",
           "Urdu"
        ],
        "billing_address":"26",
        "mac_address":"98:78:85:45:48:47",
        "stb_type":"MCBS CH4000",
        "billing_city":"Mumbai",
        "billing_pincode":"441025",
        "phone_number":"8563210258",
        "username":"balaji@mail.com",
        "email":"balaji@mail.com",
        "password":null,
        "activity_time_out":0,
        "sale_mac_address":"undefined",
        "get_msg":"Enable",
        "receive_ads":"Enable",
        "show_adult_content":"Disable",
        "account_lock":"Disable",
        "timezone":"(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi",
        "token":null,
        "billing_state":"Delhi",
        "installation_address":"26",
        "installation_city":"Mumbai",
        "installation_pincode":"441025",
        "installation_state":"Delhi",
        "landline_number":null,
        "createdAt":"2020-03-04 09:55:52",
        "updatedAt":"2020-03-04 09:55:52",
        "orgname":"Infynect Demo Operator Organization"
     },
     {
        "user_id":"bc94e73a-6ef9-4e8c-fff6-2bd646276aaa",
        "customer_id":"173436a0-5dd0-11ea-b936-1556dc150c69",
        "org_id":"489dc3b9-99dd-c57f-cfd5-dedfd5cc672d",
        "activation_code":32259809,
        "customer_firstname":"Richard",
        "customer_lastname":"",
        "language":[
           "Assamese",
           "Bangla",
           "English",
           "Gujarathi",
           "Hindi",
           "Kannada",
           "Malayalam",
           "Marathi",
           "Odia",
           "Punjabi",
           "Tamil",
           "Telugu",
           "Urdu"
        ],
        "billing_address":"269, D 42",
        "mac_address":"15:65:89:65:14:15",
        "stb_type":"MCBS CH4000",
        "billing_city":"Charkop",
        "billing_pincode":"400067",
        "phone_number":"9856321452",
        "username":"richard@mail.com",
        "email":"richard@mail.com",
        "password":null,
        "activity_time_out":0,
        "sale_mac_address":"undefined",
        "get_msg":"Enable",
        "receive_ads":"Enable",
        "show_adult_content":"Disable",
        "account_lock":"Disable",
        "timezone":"(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi",
        "token":null,
        "billing_state":"Delhi",
        "installation_address":"269, D 42",
        "installation_city":"Charkop",
        "installation_pincode":"400067",
        "installation_state":"Delhi",
        "landline_number":null,
        "createdAt":"2020-03-04 09:54:51",
        "updatedAt":"2020-03-04 09:54:51",
        "orgname":"Infynect Demo Operator Organization"
     },
     {
        "user_id":"bc94e73a-6ef9-4e8c-fff6-2bd646276aaa",
        "customer_id":"fd6d3040-5c72-11ea-81f7-1329c4b9cf72",
        "org_id":"489dc3b9-99dd-c57f-cfd5-dedfd5cc672d",
        "activation_code":18746131,
        "customer_firstname":"Rio",
        "customer_lastname":"",
        "language":[
           "Assamese",
           "Bangla",
           "English",
           "Gujarathi",
           "Hindi",
           "Kannada",
           "Malayalam",
           "Marathi",
           "Odia",
           "Punjabi",
           "Tamil",
           "Telugu",
           "Urdu"
        ],
        "billing_address":"46",
        "mac_address":"15:13:20:14:16:84",
        "stb_type":"MCBS CH4000",
        "billing_city":"Bangalore",
        "billing_pincode":"637001",
        "phone_number":"9874563210",
        "username":"rio@mail.com",
        "email":"rio@mail.com",
        "password":null,
        "activity_time_out":0,
        "sale_mac_address":"undefined",
        "get_msg":"Enable",
        "receive_ads":"Enable",
        "show_adult_content":"Disable",
        "account_lock":"Disable",
        "timezone":"(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi",
        "token":null,
        "billing_state":"Karnataka",
        "installation_address":"46",
        "installation_city":"Bangalore",
        "installation_pincode":"637001",
        "installation_state":"Karnataka",
        "landline_number":null,
        "createdAt":"2020-03-02 16:15:53",
        "updatedAt":"2020-03-02 16:15:53",
        "orgname":"Infynect Demo Operator Organization"
     },
     {
        "user_id":"bc94e73a-6ef9-4e8c-fff6-2bd646276aaa",
        "customer_id":"56fde0c0-5c71-11ea-81f7-1329c4b9cf72",
        "org_id":"489dc3b9-99dd-c57f-cfd5-dedfd5cc672d",
        "activation_code":19960607,
        "customer_firstname":"Ruba",
        "customer_lastname":"",
        "language":[
           "Assamese",
           "Bangla",
           "English",
           "Gujarathi",
           "Hindi",
           "Kannada",
           "Malayalam",
           "Marathi",
           "Odia",
           "Punjabi",
           "Tamil",
           "Telugu",
           "Urdu"
        ],
        "billing_address":"46",
        "mac_address":"12:12:12:15:14:12",
        "stb_type":"MCBS CH4000",
        "billing_city":"Namakkal",
        "billing_pincode":"637013",
        "phone_number":"9876543210",
        "username":"ruba@mail.com",
        "email":"ruba@mail.com",
        "password":null,
        "activity_time_out":0,
        "sale_mac_address":"undefined",
        "get_msg":"Enable",
        "receive_ads":"Enable",
        "show_adult_content":"Disable",
        "account_lock":"Disable",
        "timezone":"(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi",
        "token":null,
        "billing_state":"Tamilnadu",
        "installation_address":"46",
        "installation_city":"Namakkal",
        "installation_pincode":"637013",
        "installation_state":"Tamilnadu",
        "landline_number":null,
        "createdAt":"2020-03-02 16:04:04",
        "updatedAt":"2020-03-02 16:04:04",
        "orgname":"Infynect Demo Operator Organization"
     },
     {
        "user_id":"bc94e73a-6ef9-4e8c-fff6-2bd646276aaa",
        "customer_id":"a9ca0380-59db-11ea-9b95-6f8aeb4f6c4a",
        "org_id":"489dc3b9-99dd-c57f-cfd5-dedfd5cc672d",
        "activation_code":74849043,
        "customer_firstname":"Malathi",
        "customer_lastname":"",
        "language":[
           "Assamese",
           "Bangla",
           "English",
           "Gujarathi",
           "Hindi",
           "Kannada",
           "Malayalam",
           "Marathi",
           "Odia",
           "Punjabi",
           "Tamil",
           "Telugu",
           "Urdu"
        ],
        "billing_address":"46",
        "mac_address":"15:15:15:14:15:16",
        "stb_type":"MCBS CH4000",
        "billing_city":"nkl",
        "billing_pincode":"637001",
        "phone_number":"9876543210",
        "username":"bmalathii@spido.in",
        "email":"bmalathii@spido.in",
        "password":null,
        "activity_time_out":0,
        "sale_mac_address":"",
        "get_msg":"Enable",
        "receive_ads":"Enable",
        "show_adult_content":"Disable",
        "account_lock":"Disable",
        "timezone":"(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi",
        "token":null,
        "billing_state":"Sikkim",
        "installation_address":"46",
        "installation_city":"nkl",
        "installation_pincode":"637001",
        "installation_state":"Sikkim",
        "landline_number":null,
        "createdAt":"2020-02-28 20:07:36",
        "updatedAt":"2020-02-28 09:13:39",
        "orgname":"Infynect Demo Operator Organization"
     }     
  ];

  public users1 = [
     {
        "id":3,
        "user_id":"bc94e73a-6ef9-4e8c-fff6-2bd646276aaa",
        "org_name":"Infynect Demo Operator Organization",
        "roles":"OPERATOR_ADMIN",
        "first_name":"operator",
        "last_name":"",
        "password":"$2a$08$hMzMJNihRiA.LvVxQqK7/eR8Dr.8EpyihX5TwCnhfcUf53Ss6uXWe",
        "mail_id":"operator@livye.com",
        "phone_number":"9876543210",
        "org_id":"489dc3b9-99dd-c57f-cfd5-dedfd5cc672d",
        "mso_org_id":"28520dfb-168b-b3ea-2328-930594f14b42",
        "status":1,
        "createdAt":"2020-02-26 17:15:20",
        "updatedAt":"2020-02-26 17:15:20"
     },
     {
        "id":2,
        "user_id":"61573f2d-8e60-799a-ab67-fe19b8ef2ce2",
        "org_name":"Infynect Demo MSO Organization",
        "roles":"MSO_ADMIN",
        "first_name":"mso",
        "last_name":"",
        "password":"$2a$08$m81fVcz9nHOduoCBgRNX4ens3hMrhNbEiTEjcANAq3V/7P3gX22Ya",
        "mail_id":"mso@livye.com",
        "phone_number":"9876543210",
        "org_id":"28520dfb-168b-b3ea-2328-930594f14b42",
        "mso_org_id":"28520dfb-168b-b3ea-2328-930594f14b42",
        "status":1,
        "createdAt":"2020-02-26 17:14:48",
        "updatedAt":"2020-02-26 17:14:48"
     },
     {
        "id":1,
        "user_id":"911ba753-6740-4cff-940e-d10525ddb9ed",
        "org_name":"Infynect Labs Private Limited",
        "roles":"SYS_ADMIN",
        "first_name":"Infyn",
        "last_name":"Infyn",
        "password":"$2y$08$3YwiIRAPIMlUXcjmoXyr2ul8Xdelh50VYZ97O10PLekNcCRv7u6iO",
        "mail_id":"sms@livye.com",
        "phone_number":"9876543210",
        "org_id":"c0532779-ceb8-4845-b996-0ceafae15f0d",
        "mso_org_id":null,
        "status":1,
        "createdAt":"2020-02-26 10:06:40",
        "updatedAt":"2020-02-26 10:06:40"
     }
  ];

  public users = [
     {
        "id":1,
        "user_id":"50ea8b9b-ea2d-4a29-a2d1-79db242e8f2b",
        "roles":"SYS_ADMIN",
        "first_name":"Infyn",
        "last_name":"Infyn",
        "password":"$2y$08$.yZZDMNMBkfLO3FNhfZ2xu4brVokkbylif8QPQajVxSzdE67OPcgu",
        "mail_id":"drm@livye.com",
        "phone_number":"9876543210",
        "status":1,
        "createdAt":"2020-02-29 10:49:11",
        "updatedAt":"2020-02-29 10:49:11"
     }
  ]
  public page = 1;
  public pageSize = 10;
  public collectionSize = this.users.length;
  public searchKey = new FormControl('');
  private usersCopy = [];
  constructor(
    private modalService: NgbModal
  ) { }

  ngOnInit() {
    if (!this.isDrmUser) {
      this.users = this.users1;
    }
    this.usersCopy = Object.assign([], this.users);
    this.searchKey.valueChanges.pipe(
      debounceTime(700),
      map(text => search(text, this.usersCopy))
    ).subscribe((result) => {
      console.log(result);
      this.users = result;
    })
  }

  openFormModal(user?: any) {
    const modalRef = this.modalService.open(CreateUserComponent);
    modalRef.componentInstance.isDrmUser = this.isDrmUser;
    if (user) {
      modalRef.componentInstance.data = user;
    }    
    modalRef.result.then((result) => {
      console.log(result);
    }).catch((error) => {
      console.log(error);
    });
  }

}

function search(text: string, array: any[]) {
  return array.filter(user => {
    const key = text.toLowerCase();
    return user.first_name.toLowerCase().includes(key)
        || user.last_name.toLowerCase().includes(key)
        || user.mail_id.includes(key);
  });
}
